from __future__ import annotations

from collections import deque
from dataclasses import dataclass
from enum import Enum
from itertools import combinations
from typing import Iterable, Mapping


class EndpointMark(str, Enum):
    """Endpoint marks used by a PAG snapshot."""

    CIRCLE = "circle"
    ARROW = "arrow"
    TAIL = "tail"


def _edge_key(x: int, y: int) -> tuple[int, int]:
    if x == y:
        raise ValueError("Self-edges are not valid in a PAG snapshot")
    return (x, y) if x < y else (y, x)


@dataclass(frozen=True)
class PAGSnapshot:
    """Small immutable PAG view used to audit ICD-Sep enumeration.

    ``edge_marks[(u, v)]`` is stored with ``u < v`` and contains the mark at
    ``u`` followed by the mark at ``v``.  This representation is deliberately
    independent from a discovery library so expected candidates cannot be
    generated by the implementation under test.
    """

    nodes: tuple[int, ...]
    edge_marks: Mapping[tuple[int, int], tuple[EndpointMark, EndpointMark]]

    def __post_init__(self) -> None:
        if len(self.nodes) != len(set(self.nodes)):
            raise ValueError("PAG nodes must be unique")
        node_set = set(self.nodes)
        for edge, marks in self.edge_marks.items():
            if edge != _edge_key(*edge):
                raise ValueError(f"Edge key must be canonical: {edge}")
            if not set(edge).issubset(node_set):
                raise ValueError(f"Edge {edge} refers to an unknown node")
            if len(marks) != 2 or not all(isinstance(mark, EndpointMark) for mark in marks):
                raise ValueError(f"Invalid endpoint marks for {edge}: {marks}")

    @classmethod
    def circles(cls, nodes: Iterable[int], edges: Iterable[tuple[int, int]]) -> PAGSnapshot:
        canonical_nodes = tuple(sorted(set(nodes)))
        marks = {
            _edge_key(x, y): (EndpointMark.CIRCLE, EndpointMark.CIRCLE)
            for x, y in edges
        }
        return cls(canonical_nodes, marks)

    def adjacent(self, x: int, y: int) -> bool:
        return x != y and _edge_key(x, y) in self.edge_marks

    def neighbors(self, node: int) -> tuple[int, ...]:
        if node not in self.nodes:
            raise KeyError(node)
        return tuple(sorted(other for other in self.nodes if self.adjacent(node, other)))

    def mark_at(self, node: int, other: int) -> EndpointMark:
        left, right = _edge_key(node, other)
        marks = self.edge_marks[(left, right)]
        return marks[0] if node == left else marks[1]

    def is_pds_triple(self, left: int, middle: int, right: int) -> bool:
        """Return whether a triple can extend a PDS path.

        ICD Definition 2 permits a middle node when it is a definite collider
        or when the outer nodes form a triangle.
        """

        if len({left, middle, right}) != 3:
            return False
        collider = (
            self.mark_at(middle, left) == EndpointMark.ARROW
            and self.mark_at(middle, right) == EndpointMark.ARROW
        )
        return collider or self.adjacent(left, right)

    def is_possible_ancestor(self, ancestor: int, descendant: int) -> bool:
        """Implement ICD Definition 4 on the current PAG snapshot."""

        if ancestor == descendant:
            return True
        visited = {ancestor}
        queue: deque[int] = deque([ancestor])
        while queue:
            current = queue.popleft()
            for neighbor in self.neighbors(current):
                if neighbor in visited:
                    continue
                if self.mark_at(current, neighbor) == EndpointMark.ARROW:
                    continue
                if self.mark_at(neighbor, current) == EndpointMark.TAIL:
                    continue
                if neighbor == descendant:
                    return True
                visited.add(neighbor)
                queue.append(neighbor)
        return False


@dataclass(frozen=True, order=True)
class ICDSepCandidate:
    """A conditioning set satisfying the audited ICD-Sep predicate."""

    conditioning_set: tuple[int, ...]
    distance_sum: int
    witness_root: int


def _pds_paths(
    graph: PAGSnapshot,
    root: int,
    forbidden: int,
    max_depth: int,
) -> tuple[tuple[int, ...], ...]:
    if root == forbidden:
        raise ValueError("Root and forbidden endpoint must differ")
    if max_depth < 0:
        raise ValueError("max_depth must be non-negative")

    paths: list[tuple[int, ...]] = []
    queue: deque[tuple[int, ...]] = deque([(root,)])
    while queue:
        path = queue.popleft()
        if len(path) - 1 >= max_depth:
            continue
        current = path[-1]
        for neighbor in graph.neighbors(current):
            if neighbor == forbidden or neighbor in path:
                continue
            if len(path) >= 2 and not graph.is_pds_triple(path[-2], current, neighbor):
                continue
            extended = path + (neighbor,)
            paths.append(extended)
            queue.append(extended)
    return tuple(paths)


def _root_candidates(
    graph: PAGSnapshot,
    root: int,
    other: int,
    radius: int,
    require_possible_ancestor: bool,
) -> list[ICDSepCandidate]:
    paths = _pds_paths(graph, root, other, radius)
    paths_by_target: dict[int, list[tuple[int, ...]]] = {}
    min_distance: dict[int, int] = {}
    for path in paths:
        target = path[-1]
        paths_by_target.setdefault(target, []).append(path)
        min_distance[target] = min(min_distance.get(target, radius + 1), len(path) - 1)

    candidates: list[ICDSepCandidate] = []
    for selected in combinations(sorted(paths_by_target), radius):
        selected_set = set(selected)
        legal = True
        for target in selected:
            has_internal_witness = any(set(path[1:]).issubset(selected_set) for path in paths_by_target[target])
            if not has_internal_witness:
                legal = False
                break
            if require_possible_ancestor and not (
                graph.is_possible_ancestor(target, root)
                or graph.is_possible_ancestor(target, other)
            ):
                legal = False
                break
        if legal:
            candidates.append(
                ICDSepCandidate(
                    conditioning_set=tuple(selected),
                    distance_sum=sum(min_distance[node] for node in selected),
                    witness_root=root,
                )
            )
    return candidates


def enumerate_icd_sep_candidates(
    graph: PAGSnapshot,
    x: int,
    y: int,
    radius: int,
    *,
    require_possible_ancestor: bool = True,
) -> tuple[ICDSepCandidate, ...]:
    """Enumerate conditioning sets satisfying ICD-Sep for ``(x,y)`` or ``(y,x)``.

    This implements Definitions 2--4 and the ICD-Sep conditions in Rohekar et
    al. (NeurIPS 2021).  It does *not* implement the anytime-FCI orientation
    closure, so it is a reference candidate enumerator rather than a complete
    ICD round.
    """

    if radius < 0:
        raise ValueError("radius must be non-negative")
    if not graph.adjacent(x, y):
        return ()
    if radius == 0:
        return (ICDSepCandidate((), 0, x),)

    raw = _root_candidates(graph, x, y, radius, require_possible_ancestor)
    raw.extend(_root_candidates(graph, y, x, radius, require_possible_ancestor))

    best_by_set: dict[tuple[int, ...], ICDSepCandidate] = {}
    for candidate in raw:
        previous = best_by_set.get(candidate.conditioning_set)
        if previous is None or (candidate.distance_sum, candidate.witness_root) < (
            previous.distance_sum,
            previous.witness_root,
        ):
            best_by_set[candidate.conditioning_set] = candidate
    return tuple(sorted(best_by_set.values(), key=lambda item: (item.distance_sum, item.conditioning_set)))
